#!/usr/bin/env bash
# install.sh — Splunk Lab setup assistant
#
# Modes (selected from main menu):
#   Install  — check deps, create .env, start stack, wait for readiness, setup env.sh
#   Update   — stop stack, re-collect .env vars, rebuild and restart
#   Reset    — docker compose down -v, blank .env
#
# Logs all menu selections and errors to ./install.log
#
# Splunk readiness timeout (seconds) — override via environment variable:
#   SPLUNK_READY_TIMEOUT=600 ./install.sh
SPLUNK_READY_TIMEOUT=${SPLUNK_READY_TIMEOUT:-300}

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

LOG_FILE="install.log"

# ── Logging / print helpers ──────────────────────────────────────────────────
_log()     { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >> "$LOG_FILE"; }
info()     { echo -e "  ${CYAN}$*${NC}";           _log "INFO:  $*"; }
success()  { echo -e "  ${GREEN}✓ $*${NC}";        _log "OK:    $*"; }
warn()     { echo -e "  ${YELLOW}⚠  $*${NC}";      _log "WARN:  $*"; }
err()      { echo -e "  ${RED}✗ $*${NC}";          _log "ERROR: $*"; }
header()   { echo -e "\n${BOLD}${CYAN}── $* ──${NC}\n"; _log "=== $* ==="; }

# ── Dependency check ─────────────────────────────────────────────────────────
check_deps() {
  header "Checking dependencies"
  local all_ok=1

  # Docker binary
  if ! command -v docker &>/dev/null; then
    err "Docker not found"
    info "Install Docker Desktop: https://www.docker.com/products/docker-desktop/"
    all_ok=0
  # Docker daemon
  elif ! docker info &>/dev/null 2>&1; then
    err "Docker daemon is not running — start Docker Desktop and try again"
    all_ok=0
  else
    success "Docker"
  fi

  # docker compose v2
  if ! docker compose version &>/dev/null 2>&1; then
    err "docker compose (v2 plugin) not found"
    info "Update Docker Desktop or install the Compose plugin:"
    info "  https://docs.docker.com/compose/install/"
    all_ok=0
  else
    success "docker compose"
  fi

  # Claude Code CLI (non-fatal — only required for Skills)
  if ! command -v claude &>/dev/null; then
    warn "Claude Code CLI not found — required for the splunk-dashboard-gen skill"
    info "Install: https://claude.ai/code"
    info "Other lab features work without it"
    _log "WARN: claude CLI not found (non-fatal)"
  else
    success "Claude Code CLI"
  fi

  [[ $all_ok -eq 1 ]]
}

# ── .env collection ──────────────────────────────────────────────────────────
collect_env() {
  header "Configure environment"
  echo -e "  Press Enter to accept the default shown in [brackets].\n"

  # Read existing values if .env already exists
  local cur_password cur_hec_token cur_port cur_anthropic
  if [[ -f .env ]]; then
    cur_password=$(grep  '^SPLUNK_PASSWORD='   .env 2>/dev/null | cut -d= -f2-)
    cur_hec_token=$(grep '^SPLUNK_HEC_TOKEN='  .env 2>/dev/null | cut -d= -f2-)
    cur_port=$(grep      '^LAB_GUIDE_PORT='    .env 2>/dev/null | cut -d= -f2-)
    cur_anthropic=$(grep '^ANTHROPIC_API_KEY=' .env 2>/dev/null | cut -d= -f2-)
  fi

  # SPLUNK_PASSWORD — required; loop until non-empty and ≥8 chars
  local password=""
  while [[ -z "$password" ]]; do
    local default_pw="${cur_password:-Chang3d!}"
    echo -ne "  Splunk admin password [${default_pw}]: "
    read -r password
    [[ -z "$password" ]] && password="$default_pw"
    if [[ ${#password} -lt 8 ]]; then
      err "Password must be at least 8 characters"
      password=""
    fi
  done
  _log "MENU: SPLUNK_PASSWORD set"

  # SPLUNK_HEC_TOKEN — optional, defaults to a UUID
  local default_hec="${cur_hec_token:-$(uuidgen 2>/dev/null || echo "a8b4c2d6-e0f1-4321-9876-abcdef012345")}"
  echo -ne "  HEC token [${default_hec}]: "
  local hec_token
  read -r hec_token
  [[ -z "$hec_token" ]] && hec_token="$default_hec"
  _log "MENU: SPLUNK_HEC_TOKEN set"

  # LAB_GUIDE_PORT — optional
  local default_port="${cur_port:-3131}"
  echo -ne "  Lab guide port [${default_port}]: "
  local lab_port
  read -r lab_port
  [[ -z "$lab_port" ]] && lab_port="$default_port"
  _log "MENU: LAB_GUIDE_PORT=${lab_port}"

  # ANTHROPIC_API_KEY — optional
  local anthropic_display="${cur_anthropic:-<leave blank to skip Ask Splunk Chat>}"
  echo -ne "  Anthropic API key [${anthropic_display}]: "
  local anthropic_key
  read -r anthropic_key
  [[ -z "$anthropic_key" ]] && anthropic_key="${cur_anthropic:-}"
  _log "MENU: ANTHROPIC_API_KEY ${anthropic_key:+set (non-empty)}"

  # Write .env
  {
    echo "# Generated by install.sh on $(date)"
    echo ""
    echo "SPLUNK_PASSWORD=${password}"
    echo ""
    echo "SPLUNK_HEC_TOKEN=${hec_token}"
    echo ""
    echo "LAB_GUIDE_PORT=${lab_port}"
    echo ""
    if [[ -n "$anthropic_key" ]]; then
      echo "ANTHROPIC_API_KEY=${anthropic_key}"
    else
      echo "# ANTHROPIC_API_KEY=sk-ant-..."
    fi
  } > .env

  success ".env written"
  _log "MENU: .env written"
}

# ── Stack operations ─────────────────────────────────────────────────────────
start_stack() {
  header "Starting Docker stack"
  info "docker compose up -d"
  if docker compose up -d 2>&1 | tee -a "$LOG_FILE"; then
    success "Stack started"
  else
    err "docker compose up -d failed — see $LOG_FILE for details"
    return 1
  fi
}

build_stack() {
  header "Rebuilding and starting Docker stack"
  info "docker compose up -d --build"
  if docker compose up -d --build 2>&1 | tee -a "$LOG_FILE"; then
    success "Stack rebuilt and started"
  else
    err "docker compose up -d --build failed — see $LOG_FILE for details"
    return 1
  fi
}

# ── Splunk readiness poll ────────────────────────────────────────────────────
wait_for_splunk() {
  header "Waiting for Splunk"
  info "Polling for 'Ansible playbook complete' (timeout: ${SPLUNK_READY_TIMEOUT}s)"
  info "Override: SPLUNK_READY_TIMEOUT=600 ./install.sh"
  echo -ne "\n  "

  local elapsed=0
  local interval=5
  while [[ $elapsed -lt $SPLUNK_READY_TIMEOUT ]]; do
    if docker compose logs splunk 2>/dev/null | grep -q "Ansible playbook complete"; then
      echo
      success "Splunk ready (${elapsed}s)"
      _log "Splunk ready after ${elapsed}s"
      return 0
    fi
    echo -n "."
    sleep "$interval"
    elapsed=$(( elapsed + interval ))
  done

  echo
  err "Splunk did not reach readiness within ${SPLUNK_READY_TIMEOUT}s"
  warn "Check logs: docker compose logs -f splunk"
  _log "ERROR: Splunk readiness timeout after ${SPLUNK_READY_TIMEOUT}s"
  return 1
}

# ── Status summary ───────────────────────────────────────────────────────────
check_status() {
  header "Service status"

  echo "  Containers:"
  docker compose ps --format "table {{.Name}}\t{{.Status}}" 2>/dev/null \
    | tail -n +2 \
    | while IFS= read -r line; do echo "    $line"; done

  echo
  echo -ne "  MCP server (localhost:8050): "
  local http_code
  http_code=$(curl -s --max-time 5 -o /dev/null -w "%{http_code}" \
    -X POST -H "Content-Type: application/json" -d '{}' \
    http://localhost:8050/mcp 2>/dev/null)
  if [[ -n "$http_code" && "$http_code" != "000" ]]; then
    success "reachable (HTTP ${http_code})"
    _log "MCP reachable HTTP ${http_code}"
  else
    warn "not yet reachable — may still be starting"
    _log "WARN: MCP not reachable after stack start"
  fi

  echo
  local port
  port=$(grep '^LAB_GUIDE_PORT=' .env 2>/dev/null | cut -d= -f2- || echo 3131)
  echo -e "  Lab guide → ${CYAN}http://localhost:${port}${NC}"
  echo -e "  Splunk Web → ${CYAN}http://localhost:8000${NC}"
  echo -e "  MCP endpoint → ${CYAN}http://localhost:8050/mcp${NC}"
}

# ── env.sh skill setup ───────────────────────────────────────────────────────
setup_env_sh() {
  header "Skill setup — \$HOME/.claude/env.sh"
  echo "  The splunk-dashboard-gen skill needs credentials in \$HOME/.claude/env.sh."
  echo "  This is separate from .env (which is only read by Docker Compose)."
  echo

  local env_sh="$HOME/.claude/env.sh"

  if [[ -f "$env_sh" ]]; then
    success "env.sh already exists at $env_sh"
    echo -ne "  Overwrite with values from this lab? [y/N]: "
    local overwrite
    read -r overwrite
    _log "MENU: env.sh overwrite prompt → ${overwrite}"
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
      info "Skipped — existing env.sh kept"
      return 0
    fi
  fi

  # Pull SPLUNK_PASSWORD from .env to populate SPLUNK_PASS in env.sh
  local splunk_pass
  splunk_pass=$(grep '^SPLUNK_PASSWORD=' .env 2>/dev/null | cut -d= -f2-)

  mkdir -p "$HOME/.claude"
  cp env.sh.example "$env_sh"

  # Substitute SPLUNK_PASS — macOS sed needs '' after -i, Linux doesn't
  if [[ "$(uname)" == "Darwin" ]]; then
    sed -i '' "s|^export SPLUNK_PASS=.*|export SPLUNK_PASS=${splunk_pass}|" "$env_sh"
  else
    sed -i "s|^export SPLUNK_PASS=.*|export SPLUNK_PASS=${splunk_pass}|" "$env_sh"
  fi

  chmod 600 "$env_sh"
  success "env.sh written to $env_sh (permissions: 600)"
  _log "env.sh written to $env_sh"
}

# ── Mode: install ────────────────────────────────────────────────────────────
do_install() {
  check_deps || {
    err "Fix the above issues and re-run install"
    return 1
  }
  collect_env
  start_stack || return 1
  wait_for_splunk
  check_status

  echo
  echo -ne "  Set up \$HOME/.claude/env.sh for the splunk-dashboard-gen skill? [Y/n]: "
  local do_skill
  read -r do_skill
  _log "MENU: skill setup prompt → ${do_skill}"
  if [[ ! "$do_skill" =~ ^[Nn]$ ]]; then
    setup_env_sh
  fi

  echo
  success "Lab is ready."
  _log "Install complete"
}

# ── Mode: update ─────────────────────────────────────────────────────────────
do_update() {
  header "Update — reconfigure and rebuild"
  info "Stopping containers..."
  docker compose down 2>&1 | tee -a "$LOG_FILE"
  _log "MENU: update — stack stopped"

  collect_env
  build_stack || return 1
  wait_for_splunk
  check_status

  _log "Update complete"
  success "Update complete"
}

# ── Mode: reset ──────────────────────────────────────────────────────────────
do_reset() {
  header "Reset — destroy stack and clear .env"
  warn "docker compose down -v will delete all containers and volumes."
  warn "All indexed Splunk data will be permanently lost."
  echo
  echo -ne "  Type 'reset' to confirm: "
  local confirm
  read -r confirm
  _log "MENU: reset confirm → ${confirm}"

  if [[ "$confirm" != "reset" ]]; then
    info "Reset cancelled"
    return 0
  fi

  info "docker compose down -v"
  if docker compose down -v 2>&1 | tee -a "$LOG_FILE"; then
    success "Stack destroyed"
    _log "Stack destroyed"
  else
    err "docker compose down -v failed — see $LOG_FILE"
    _log "ERROR: docker compose down -v failed"
  fi

  # Write a blank .env
  {
    echo "# Reset by install.sh on $(date) — fill in values and re-run Install"
    echo ""
    echo "SPLUNK_PASSWORD="
    echo "SPLUNK_HEC_TOKEN="
    echo "LAB_GUIDE_PORT=3131"
    echo "# ANTHROPIC_API_KEY="
  } > .env

  success ".env reset to blank values"
  _log ".env reset"
}

# ── Main menu ────────────────────────────────────────────────────────────────
main_menu() {
  while true; do
    echo
    echo -e "${BOLD}${CYAN}╔══════════════════════════════╗${NC}"
    echo -e "${BOLD}${CYAN}║    Splunk Lab  ·  Installer  ║${NC}"
    echo -e "${BOLD}${CYAN}╚══════════════════════════════╝${NC}"
    echo
    echo "    1)  Install   — first-time setup"
    echo "    2)  Update    — reconfigure and rebuild"
    echo "    3)  Reset     — destroy stack and clear .env"
    echo "    4)  Quit"
    echo
    echo -ne "  Select [1-4]: "
    local choice
    read -r choice
    _log "MENU: main menu → ${choice}"

    case "$choice" in
      1) do_install ;;
      2) do_update ;;
      3) do_reset ;;
      4) echo; info "Bye."; exit 0 ;;
      *) warn "Invalid selection — enter 1, 2, 3, or 4" ;;
    esac
  done
}

# ── Entry point ──────────────────────────────────────────────────────────────
# Always run from the repo root (where docker-compose.yml lives)
cd "$(dirname "$0")"

_log "=== install.sh started ==="
main_menu
