# Define the buttercup index — created automatically when Splunk loads this app
[buttercup]
homePath   = $SPLUNK_DB/buttercup/db
coldPath   = $SPLUNK_DB/buttercup/colddb
thawedPath = $SPLUNK_DB/buttercup/thaweddb
