# Tell Splunk how to parse the CSV files — first row is the header

[buttercup_sales]
INDEXED_EXTRACTIONS = csv
FIELD_HEADER_REGEX = 0

[buttercup_products]
INDEXED_EXTRACTIONS = csv
FIELD_HEADER_REGEX = 0
