[drop_comment_lines]
REGEX = ^\s*#
DEST_KEY = queue
FORMAT = nullQueue

[route_by_sourcetype]
SOURCE_KEY = MetaData:Sourcetype
REGEX = sourcetype::(buttercup_.*)
DEST_KEY = _MetaData:Index
FORMAT = buttercup
