#!/bin/bash
# install-splunk.sh - Install Docker Engine and deploy the Splunk container inside the LXC

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/../.env"

if [[ ! -f "$ENV_FILE" ]]; then
    echo "Error: .env file not found at $ENV_FILE"
    echo "Copy .env.example to .env and configure your values."
    exit 1
fi

source "$ENV_FILE"
source "${SCRIPT_DIR}/lib.sh"

SPLUNK_COMPOSE_DIR="${SPLUNK_COMPOSE_DIR:-/opt/splunk-docker}"

echo "==> Installing Splunk Enterprise (Docker) on LXC ${LXC_IP_ADDR}"

# ---------------------------------------------------------------------------
# 1. Install Docker Engine
# ---------------------------------------------------------------------------
echo "==> Installing Docker Engine..."
lxc_ssh "apt-get update -qq && apt-get install -y ca-certificates curl gnupg"
lxc_ssh "install -m 0755 -d /etc/apt/keyrings \
    && curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
       | gpg --dearmor -o /etc/apt/keyrings/docker.gpg \
    && chmod a+r /etc/apt/keyrings/docker.gpg"
lxc_ssh 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    | tee /etc/apt/sources.list.d/docker.list > /dev/null'
lxc_ssh "apt-get update -qq && apt-get install -y \
    docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin"
lxc_ssh "systemctl enable docker && systemctl start docker"
echo "==> Docker Engine installed."

# ---------------------------------------------------------------------------
# 2. Create data directories
# ---------------------------------------------------------------------------
echo "==> Creating Splunk data directories..."
lxc_ssh "mkdir -p ${SPLUNK_COMPOSE_DIR} /opt/splunk/var /opt/splunk/etc /opt/splunk-import"

# ---------------------------------------------------------------------------
# 3. Deploy docker-compose.yml
# ---------------------------------------------------------------------------
echo "==> Copying docker-compose.yml..."
lxc_scp "${SCRIPT_DIR}/../docker-compose.yml" "root@${LXC_IP_ADDR}:${SPLUNK_COMPOSE_DIR}/docker-compose.yml"

# ---------------------------------------------------------------------------
# 4. Generate compose .env (Splunk runtime vars only — no infra secrets)
# ---------------------------------------------------------------------------
echo "==> Writing compose .env..."
compose_env="# Generated by install-splunk.sh — do not edit manually
SPLUNK_IMAGE=${SPLUNK_IMAGE:-splunk/splunk:latest}
SPLUNK_MEMORY_LIMIT=${SPLUNK_MEMORY_LIMIT:-8G}
SPLUNK_MEMORY_RESERVATION=${SPLUNK_MEMORY_RESERVATION:-4G}
SPLUNK_START_ARGS=--accept-license
SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
SPLUNK_PASSWORD=${SPLUNK_ADMIN_PASSWORD}
SPLUNK_ROLE=${SPLUNK_ROLE:-splunk_standalone}
SPLUNK_LICENSE_URI=${SPLUNK_LICENSE_URI:-Free}"

if [[ -n "${SPLUNK_HEC_TOKEN:-}" ]]; then
    compose_env="${compose_env}
SPLUNK_HEC_TOKEN=${SPLUNK_HEC_TOKEN}"
fi

printf '%s\n' "${compose_env}" | lxc_ssh "cat > ${SPLUNK_COMPOSE_DIR}/.env"

# ---------------------------------------------------------------------------
# 5. Start the stack
# ---------------------------------------------------------------------------
echo "==> Starting Splunk container..."
lxc_ssh "cd ${SPLUNK_COMPOSE_DIR} && docker compose up -d"

echo ""
echo "==> Splunk container started. Run configure-splunk.sh to verify readiness."
echo "    Web UI: http://${LXC_IP_ADDR}:${SPLUNK_HTTP_PORT:-8000}"
