server {
    listen 80;
    root  /usr/share/nginx/html;
    index index.html;

    # Proxy status API requests to the status-api container
    location /api/status {
        proxy_pass         http://status-api:8081/api/status;
        proxy_read_timeout 5s;
        proxy_connect_timeout 2s;
        add_header         Cache-Control "no-cache, no-store";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
